package clue.less;

public enum Card {
	HALL, LIBRARY, KITCHEN, STUDY, LOUNGE, BILLARD, DINING, BALLROOM, CONSERVATORY,
	GREEN, MUSTARD, SCARLET, PLUM, PEACOCK, WHITE,
	CANDLESTICK, WRENCH, PIPE, REVOLVER, ROPE, KNIFE
}
