package clue.less

import clue.less.GameFullException
import clue.less.Player

class GameState {	
	
	/**
	 * This will be the UUID of the game
	 * it is automatically generated by the database and is immuttable
	 */
	long id
	
	static constraints = {
		player1 nullable: true
		player2 nullable: true
		player3 nullable: true
		player4 nullable: true
		player5 nullable: true
		player6 nullable: true
	}
	
	static transients = ['playerCount']
	
	// Having each player as an instance variable instead of an array, we simplify hibernate configuration to 0
	Player player1
	
	Player player2
	
	Player player3
	
	Player player4
	
	Player player5
	
	Player player6

	// used for getting the initial solution cards
	Random random = new Random()
	
	/**
	 * User name for the created game.
	 */
	String name
	
	/**
	 * Flag indicating if the game has started yet for joining.
	 */
	boolean gameStarted
	
	/**
	 * Card representing the winning weapon.
	 */
	Weapon solutionWeapon
	
	/**
	 * Card representing the winning location.
	 */
	Location solutionLocation
	
	/**
	 * Card representing the winning suspect.
	 */
	Suspect solutionSuspect
	
	/**
	 * Default constructor required by hibernate
	 */
	public GameState(){
		createGame(""+new Date())
	}

	
	public GameState createGame(String name){
		generateRandomSolution()
		this.name = name?:""+new Date()
		gameStarted = false
		return this
	}
	
	private void generateRandomSolution(){
		// get a random card for the weapon solution
		solutionWeapon = Weapon.values()[random.nextInt(Weapon.values().size()-1)]
		// get a random card for the location solution
		solutionLocation = Location.values()[random.nextInt(Location.getNonHallways().size()-1)]
		// get a random card for the suspect solution
		solutionSuspect = Suspect.values()[random.nextInt(Suspect.values().size()-1)]
	}
	
	private void generatePlayers(){
		player1 = new Player()
		player1.gameState = this
		player1.save()
		player2 = new Player()
		player2.gameState = this
		player2.save()
		player3 = new Player()
		player3.gameState = this
		player3.save()
		player4 = new Player()
		player4.gameState = this
		player4.save()
		player5 = new Player()
		player5.gameState = this
		player5.save()
		player6 = new Player()
		player6.gameState = this
		player6.save()
	}
	
	public Player claimSeat(){
		for(Player p: getPlayers()){
			if(!p.claimed){
				p.claimed = true
				return p
			}
		}
		throw new GameFullException("No Seats available")
	}
	
	int getPlayerCount(){
		int x = 0
		for(Player p: getPlayers()){
			if(p.claimed){
				x++
			}
		}
		return x
	}
	
	public Player[] getPlayers(){
		return [player1, player2, player3, player4, player5, player6]
	}
}
