package clue.less;

public enum Location{
	HALL, LIBRARY, KITCHEN, STUDY, LOUNGE, BILLARD, DINING, BALLROOM, CONSERVATORY, HALLWAY1, 
	HALLWAY2, HALLWAY3, HALLWAY4, HALLWAY5, HALLWAY6, HALLWAY7, HALLWAY8, HALLWAY9, HALLWAY10,
	HALLWAY11, HALLWAY12
}
